Repository UCLH-Foundry/PIXL, pull requests merged in 2024-02, with the labels that each got.

#279 Jstutters/dependabot-2-update-fastapi-to-0.190.1
  hasher/pyproject.toml
  pixl_core/pyproject.toml
  test/dummy-services/cogstack/pyproject.toml
Labels: security

#298 Use alembic for database table creation
  cli/src/pixl_cli/main.py
  docker-compose.yml
  docker/imaging-api/Dockerfile
  docker/postgres/Dockerfile
  pixl_imaging/README.md
  pixl_imaging/alembic/README.md
  pixl_imaging/alembic/alembic.ini
  pixl_imaging/alembic/autogenerate-migration.sh
  pixl_imaging/alembic/env.py
  pixl_imaging/alembic/migrations.env
  pixl_imaging/alembic/script.py.mako
  pixl_imaging/alembic/versions/bcaef54e2bfe_create_extract_and_image_tables.py
  pixl_imaging/pyproject.toml
  pixl_imaging/scripts/migrate_and_run.sh
  pixl_imaging/tests/docker-compose.yml
  pixl_imaging/tests/run-tests.sh
  postgres/README.md
  postgres/pixl-db_init.sh
  ruff.toml
  test/.env
Labels: improvement

#280 Add documentation for Parquet files and export process
  README.md
  docs/file_types/parquet_files.md
  docs/services/ftp-server.md
  pixl_core/README.md
  pixl_core/src/core/exports.py
  pixl_core/src/core/upload.py
Labels: documentation
